<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="W10N-I8E09" failures="2" tests="7" name="proyecto_division.DivisionTest" time="0.152" errors="0" timestamp="12 Feb 2021 20:59:59 GMT">
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC1 on testCalcularDivisionC1(proyecto_division.DivisionTest)" time="0.014"/>
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC2 on testCalcularDivisionC2(proyecto_division.DivisionTest)" time="0.0"/>
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC3 on testCalcularDivisionC3(proyecto_division.DivisionTest)" time="0.0">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;4.1181E-84&amp;gt; but was:&amp;lt;0.0&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<4.1181E-84> but was:<0.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at proyecto_division.DivisionTest.testCalcularDivisionC3(DivisionTest.java:78)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCalcularDivisionC3 on testCalcularDivisionC3(proyecto_division.DivisionTest) -->
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC4 on testCalcularDivisionC4(proyecto_division.DivisionTest)" time="0.0">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;2.4283E83&amp;gt; but was:&amp;lt;Infinity&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<2.4283E83> but was:<Infinity>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at proyecto_division.DivisionTest.testCalcularDivisionC4(DivisionTest.java:86)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCalcularDivisionC4 on testCalcularDivisionC4(proyecto_division.DivisionTest) -->
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC5 on testCalcularDivisionC5(proyecto_division.DivisionTest)" time="0.0"/>
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC6 on testCalcularDivisionC6(proyecto_division.DivisionTest)" time="0.0"/>
  <testcase classname="proyecto_division.DivisionTest" name="testCalcularDivisionC7 on testCalcularDivisionC7(proyecto_division.DivisionTest)" time="0.0"/>
</testsuite> <!-- proyecto_division.DivisionTest -->
